#if !defined(PARAMETERS_H)
#define PARAMETERS_H

//219 -> 110
#define GRAYSCALE_THRESHOLD 120
#define CELL_SEARCH_RADIUS 8
#define MAX_OVERLAP_RADIUS 10

#define POINTS_LENGTH 400
#define CROSS_R_SIZE 8

#endif // PARAMETERS_H
