#ifndef STATES_ENUM_H
#define STATES_ENUM_H   

typedef enum{
    INIT,
    LOAD_FILE,
    RGB_TO_GRAY,
    GRAY_TO_BW,
    ERODE_IMAGE,
    CHECK_ENRODED_IMAGE,
    INIT_ANALYSIS,
    DETECT_CELLS,
    MARK_POINTS,
    PRINT_ERODE_IMAGE,
    EXIT
}STATES;


#endif // STATES_ENUM_H
